export const PAGE_URL = {
  MAIN: '/',
  LOGIN: '/login',
  REGIST: '/regist',
  LIVE_DETAIL: '/live',
  REPLAY_DETAIL: '/replay',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  EMAIL_VERIFY: '/email-verify',
  EMAIL_VERIFY_SUCCESS: '/email-success',
  EMAIL_VERIFY_FAIL: '/email-fail',
  STREAM: '/stream',
  MY_PAGE: '/mypage',
  MY_STUDIO: '/studio',
  MY_STUDIO_EDIT: '/studio/edit',
  FAQ: '/faq',
  NOTICE: '/notice',
  MY_CHANNEL: '/channel',
  CHANNEL_COMMUNITY: '/community',
  CHANNEL_COMMUNITY_DETAIL: '/community/detail',
  CHANNEL_ABOUT: '/about',
  ABOUT_US: '/aboutus',
};
